### ISSUE TITLE
Get error when trying to connect to server.

### ISSUE THREAD

**Issue by toErIpNid** [Sirttas/ElementalCraft#48] opened 2021-04-03 18:41 UTC
**Describe the bug**
Can't connect to server with elemental craft installed.

**To Reproduce**
1. Create a server with elemental craft. 
2. Attempt to connect.
3. Get this when trying to connect: 
![Error](https://user-images.githubusercontent.com/78389307/113488195-273e8480-9482-11eb-80e2-112aea871277.PNG)

**Expected behavior**
I expected it to work normally so I can actually play on the server.

**ModPack**
Private modpack. Modlist: 
![modlist](https://user-images.githubusercontent.com/78389307/113488219-46d5ad00-9482-11eb-9254-775c80e4d18a.PNG)

**Comment by Sirttas** [comment] 2021-04-03 18:42
Duplicate of #47

**Closed as completed by Sirttas** 2021-04-03 18:42 UTC
Labels: duplicate, invalid
