### ISSUE TITLE
[1.18.2-1.19.2] JewelHandler tick performance. (profiler included).

### ISSUE THREAD

**Issue by Gbergz** [Sirttas/ElementalCraft#81] opened 2022-04-24 20:49 UTC
**Describe the bug**
JewelHandler taking up 22% of onServer Ticks. (profiler included).

**To Reproduce**
Steps to reproduce the behavior: (Not entirely sure, but for our server it's just starting it up and wait a bit.)
1. Start server 
2. wait a bit
3. join.
4. run profiler w/ spark
5. JewelHandler taking up 22+% of the performance. TPS dropping.

**Expected behavior**
No significant tps drops due to the JewelHandler.

**ModPack**
https://www.curseforge.com/minecraft/modpacks/tnp-limitless-5

**Profiler**
https://spark.lucko.me/U559AVPhGX

**Versions**
Minecraft: 1.18.2
Forge: 40.1.0
ElementalCraft: elementalcraft-1.18.2-4.3.3
DP Anvil: dpanvil-1.18.2-3.3.2c

**More info**
I did see that a new update was released to improve Jewel Performance, but I tried it, still tps dipping.

**Comment by NachtRaben** [comment] 2022-04-25 03:30
https://github.com/AllTheMods/ATM-7/issues/702

Confirmed this a continuation of the bug present in 4.3.2
See attached threads and spark profiles of the system.

**Comment by Sirttas** [comment] 2022-04-25 07:30
Should be fixed in 4.3.4

**Comment by Mowmaster** [comment] 2022-10-03 00:22
Still seems to be causing issues in version 5.4.6 (All the mod 8 v0.0.15)
https://spark.lucko.me/e59BTfxMyU

**Comment by Sirttas** [comment] 2022-10-03 02:54
@Mowmaster can you send me a world export?

**Comment by Sirttas** [comment] 2022-10-03 17:34
Fixed in 1.19.2-5.5.1

**Closed as completed by Sirttas** 2022-10-03 17:34 UTC
Labels: bug, performance
