### ISSUE TITLE
Earth infusion worsens enchanted item

### ISSUE THREAD

**Issue by uhloin** [Sirttas/ElementalCraft#124] opened 2022-12-16 19:31 UTC
**Describe the bug**
Sharpness +1 from infusion replaces current greater Sharpness +5.

**To Reproduce**
Create Poison Saber from DivineRPG (damage 16), enchant to Sharpness +5 (damage increased to 19), infuse with earth element (damage decreased to 17).

**Expected behavior**
Add Sharpness to current, not replace it.

**Comment by uhloin** [comment] 2022-12-16 19:33
Bug #2
The same Saber infused with Air Element write strange description:

When in Main hand:
2.3 Attack Speed
4.8 Attack Speed
Air Infused (+0.8 Attack Speed)

Before infusion:
When in Main hand:
2.3 Attack Speed

**Comment by uhloin** [comment] 2022-12-16 19:39
Bug #3
Water infusion shows tooltip "Looting +1" but 
Fire infusion does not show similar tooltip "Fire Aspect +1"

Also check please if that Looting +1 replaces current enchantment Looting +3 instead of add and make +4.

**Comment by Sirttas** [comment] 2023-01-22 18:49
I fixed bug 1, bug 2 seems just to be a render error because of attributes UUID, I cant reproduce bug 3.

also: 
> Also check please if that Looting +1 replaces current enchantment Looting +3 instead of add and make +4.

is the same as bug 1 so it is fixed too.

**Comment by Sirttas** [comment] 2023-01-22 20:34
fixed in 5.5.9

**Closed as completed by Sirttas** 2023-01-22 20:34 UTC
Labels: bug
