### ISSUE TITLE
Element Infuser doesn't use the last point of water to create a Drenched Ingot

### ISSUE THREAD

**Issue by Filostorm** [Sirttas/ElementalCraft#104] opened 2022-08-26 11:09 UTC
Element Infuser doesn't use the last point of water to create a Drenched Ingot

I'm assuming this is for all recipes in the Element Infuser.

**To Reproduce**
Fill Small Element Container with 500 Water. (Extracted from 2 Raw Water Shards)
Place an Iron Ingot in an attached Elemental Infuser.
Watch as it infuses 499 water into the ingot.

Note: The recipe works fine if you supply any amount more Water, for example if I melt another 2 shards, it will complete that craft and pause at 1 remaining again.

**Expected behavior**
It to use all 500 Water to actually do the craft

**ModPack**
Custom pack with very little changed settings

**Comment by Filostorm** [comment] 2022-08-26 11:09
![2022-08-26_07 02 54](https://user-images.githubusercontent.com/73716145/186891158-0e13e6ce-3abd-49b3-b5ff-6f1fc5b6a0fe.png)

**Comment by Sirttas** [comment] 2022-08-26 12:18
What version are you on.

**Comment by Sirttas** [comment] 2022-08-26 12:19
Also I just realized it is an intended behavior to not reset the element type of the container and cancel the recipe.

**Comment by Filostorm** [comment] 2022-08-26 22:40
1.18. 
I thought it might be, and I suppose its only really an issue in fringe cases.

**Comment by Filostorm** [comment] 2022-11-30 11:17
Going to reopen this, I feel like its a more likely case in early game where you are crafting with shards (had it happen while playing just now). 

It seems like it would make more sense to reset the craft by purposefully adding a new element to the container then to not craft the item when there is technically enough to do so.

**Comment by Sirttas** [comment] 2023-01-15 19:51
fixed in 5.5.8

**Closed as completed by Sirttas** 2023-01-15 19:51 UTC
Labels: bug
