### ISSUE TITLE
Crash on attempt to add two items to anvil

### ISSUE THREAD

**Issue by VentedSun** [Sirttas/ElementalCraft#92] opened 2022-06-20 18:02 UTC
1.16.5
ATM Spellbound 2.2.7
elementalcraft-1.16.5-2.7.14.jar

Combining one item with an infusion and one without causes the game to lock up and crash out to desktop.

**Comment by Sirttas** [comment] 2022-06-20 18:51
Can you provide a crash report please?

**Comment by Sirttas** [comment] 2022-07-27 11:55
As you failed to provide a crash report and I cannot reproduce I'm closing this issue. Please open a new one with a crash report.

**Closed as completed by Sirttas** 2022-07-27 11:55 UTC
Labels: Crash
