### ISSUE TITLE
[1.17.1] Server not joinable when ElementalCraft is installed. (Internal Exception)

### ISSUE THREAD

**Issue by Gbergz** [Sirttas/ElementalCraft#53] opened 2021-08-04 09:43 UTC
**Describe the bug**
Server not joinable when ElementalCraft (1.17.1) is installed. (Internal Exception.)

**To Reproduce**
1. Install ElementalCraft on a clean instance.
2. Install a server with ElementalCraft
3. Join server.
4. Error. Disconnect.

**Expected behavior**
Joinable and playable.

**LOGS**
https://gist.github.com/Gbergz/b7673dfd8a8bd4627f8fbd59c6c7ec41

*Disconnect Screen**
![2021-08-04_11 43 06_2](https://user-images.githubusercontent.com/26634554/128159666-38c3f234-a94c-4c0e-abf6-22ac5ec341e2.png)

**ModPack**
No modpack, clean instance with just ElementalCraft + the dependency mod.

**-** Gbergz

**Comment by Sirttas** [comment] 2021-08-04 13:08
this is caused by: https://github.com/MinecraftForge/MinecraftForge/issues/7933.

**Comment by Sirttas** [comment] 2021-08-10 05:50
Fixed by forge.

**Closed as completed by Sirttas** 2021-08-10 05:50 UTC
Labels: bug
