### ISSUE TITLE
Binder gives a world breaking ticking entity crash

### ISSUE THREAD

**Issue by LukeCronquist** [Sirttas/ElementalCraft#37] opened 2021-02-02 20:07 UTC
Trying to make swift alloy.

Pack is TNP Limitless 3

Ticking block entity

**Comment by Sirttas** [comment] 2021-02-02 20:10
Duplicate of https://github.com/Sirttas/ElementalCraft/issues/31 fixed in last version

**Closed as completed by Sirttas** 2021-02-02 20:10 UTC
Labels: duplicate, invalid, Crash
