### ISSUE TITLE
Suggestion: Growth shrine should work on pumpkins and melons

### ISSUE THREAD

**Issue by cleavera** [Sirttas/ElementalCraft#38] opened 2021-02-05 18:33 UTC
Firstly to say I'm very much enjoying your mod.

I've noticed that the growth shrine works on the stems of pumpkins and melons but it would be great if it also sped up the actual growing of the pumpkins/melons themselves

**Comment by Sirttas** [comment] 2021-03-02 10:35
The issue is that once the stem is fully grown it `canGrow` is `false`. I could bypass this check but it would mean that having a growth shrine with only a single melon seed would be giving 1 melon per second (even more with acceleration upgrades.

the solutions are either do nothing, or add an new shrine upgrade for this case.

**Comment by cleavera** [comment] 2021-03-02 14:08
I guess a new upgrade makes sense, allows the shrine to send growth ticks to crops that are already fully grown but does it less often?

**Comment by Sirttas** [comment] 2021-03-04 09:28
That's why I created shrine upgrades. They are here to offer various (similar) behavior to shrine with each one having its own balance.

**Comment by Sirttas** [comment] 2021-03-14 20:52
Fixed in 2.6.3

**Closed as completed by Sirttas** 2021-03-14 20:52 UTC
Labels: enhancement
