### ISSUE TITLE
[1.19.2] Crash feature placement

### ISSUE THREAD

**Issue by itsdinkd** [Sirttas/ElementalCraft#143] opened 2023-05-06 20:21 UTC
log; https://gist.github.com/itsdinkd/163862ab4eea9c564ad1bd34ebee00bf 

Seems everytime I try to add Elemental Craft into my modpacks, in 1.18.1, 1.18.2, and now 1.19.2, there is always an issue, unfortunately. 

In order to debug `Accessing LegacyRandomSource from multiple threads` I had a add a mod that specifically debugs this. (Which is why you see the messages in the stack trace below. 

Original: 

![image](https://user-images.githubusercontent.com/35115304/236645231-af94d3b8-5486-4f3c-850c-34205323d2a0.png)

With the debugger, which points out that elemental craft caused this ->

```
[14:07:00] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Feature placement
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.ishland.uwrad.common.CheckedThreadLocalRandom$1: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: Worker-Main-10)
Possible solutions: Find possible causes in the stack trace below and report to the corresponding mod authors 
 
 (You may make this a fatal warning instead of a hard crash with enforce_safe_world_random_access setting in uwrad.properties)
Caused by: java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: Worker-Main-10)
	at com.ishland.uwrad.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:51) ~[unsafe-world-random-access-detector-1.1.0forge.jar%23778!/:?]
	at com.ishland.uwrad.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38) ~[unsafe-world-random-access-detector-1.1.0forge.jar%23778!/:?]
	at com.ishland.uwrad.common.CheckedThreadLocalRandom.m_64707_(CheckedThreadLocalRandom.java:82) ~[unsafe-world-random-access-detector-1.1.0forge.jar%23778!/:?]
	at net.minecraft.world.level.levelgen.BitRandomSource.m_188501_(BitRandomSource.java:56) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at sirttas.elementalcraft.block.source.trait.value.ChanceSourceTraitValueProvider.roll(ChanceSourceTraitValueProvider.java:42) ~[elementalcraft-1.19.2-5.8.1.jar%23585!/:1.19.2-5.8.1]
	at sirttas.elementalcraft.block.source.trait.value.PredicateSourceTraitValueProvider.roll(PredicateSourceTraitValueProvider.java:37) ~[elementalcraft-1.19.2-5.8.1.jar%23585!/:1.19.2-5.8.1]
	at sirttas.elementalcraft.api.source.trait.SourceTrait.roll(SourceTrait.java:58) ~[elementalcraft-1.19.2-5.8.1.jar%23585!/:1.19.2-5.8.1]
	at sirttas.elementalcraft.block.source.trait.holder.SourceTraitHolder.initTraits(SourceTraitHolder.java:50) ~[elementalcraft-1.19.2-5.8.1.jar%23585!/:1.19.2-5.8.1]
	at sirttas.elementalcraft.block.source.SourceBlockEntity.initTraits(SourceBlockEntity.java:67) ~[elementalcraft-1.19.2-5.8.1.jar%23585!/:1.19.2-5.8.1]
	at sirttas.elementalcraft.block.source.SourceBlockEntity.resetTraits(SourceBlockEntity.java:73) ~[elementalcraft-1.19.2-5.8.1.jar%23585!/:1.19.2-5.8.1]
	at sirttas.elementalcraft.world.feature.SourceFeature.lambda$placeSource$0(SourceFeature.java:56) ~[elementalcraft-1.19.2-5.8.1.jar%23585!/:1.19.2-5.8.1]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at sirttas.elementalcraft.world.feature.SourceFeature.placeSource(SourceFeature.java:56) ~[elementalcraft-1.19.2-5.8.1.jar%23585!/:1.19.2-5.8.1]
	at sirttas.elementalcraft.world.feature.structure.SourceAltarStructure$Piece.m_213704_(SourceAltarStructure.java:117) ~[elementalcraft-1.19.2-5.8.1.jar%23585!/:1.19.2-5.8.1]
	at net.minecraft.world.level.levelgen.structure.TemplateStructurePiece.m_213694_(net/minecraft/world/level/levelgen/structure/TemplateStructurePiece.java:95) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at sirttas.elementalcraft.world.feature.structure.SourceAltarStructure$Piece.m_213694_(SourceAltarStructure.java:108) ~[elementalcraft-1.19.2-5.8.1.jar%23585!/:1.19.2-5.8.1]
	at net.minecraft.world.level.levelgen.structure.StructureStart.m_226850_(net/minecraft/world/level/levelgen/structure/StructureStart.java:89) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_223080_(net/minecraft/world/level/chunk/ChunkGenerator.java:429) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23121!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(net/minecraft/world/level/chunk/ChunkGenerator.java:428) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_223313_(ChunkStatus.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_223279_(ChunkStatus.java:292) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(net/minecraft/server/level/ChunkMap.java:621) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(net/minecraft/server/level/ChunkMap.java:619) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.19.2-20220805.130853-srg.jar%23799!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by Sirttas** [comment] 2023-05-06 20:25
this seems to be caused by this mod: https://modrinth.com/mod/uwrad

**Comment by Sirttas** [comment] 2023-05-06 20:56
Sorry to hear you have been struggling with elementalcraft, the fact its only a couple people are testing new versions as soon as they release, each times a new big version is relesased a lot of issues can slip in. That's why this kind of bug report are primordial for mods.

**Comment by Sirttas** [comment] 2023-05-06 21:03
Fixed in 5.8.3

**Closed as completed by Sirttas** 2023-05-06 21:03 UTC
Labels: Crash

**Comment by itsdinkd** [comment] 2023-05-06 21:06
> Sorry to hear you have been struggling with elementalcraft, the fact its only a couple people are testing new versions as soon as they release, each times a new big version is relesased a lot of issues can slip in. That's why this kind of bug report are primordial for mods.

Appreciate it. I'm always happy to report issues. I just really want to play elemental craft in my packs haha. hoping this next version plays well, thanks for the quick update.

Seems I had bad timing and added the mod when a big version came out

**Comment by Sirttas** [comment] 2023-05-06 21:22
Thank you for your understanding.
