### ISSUE TITLE
Particlehelper crashes server

### ISSUE THREAD

**Issue by xeesus** [Sirttas/ElementalCraft#16] opened 2020-11-13 18:58 UTC
Putting an inert crystal into the infuser (when it's ready to infuse) causes the server to crash.
[Crash report](https://github.com/Sirttas/ElementalCraft/files/5538797/crash-2020-11-13_21.52.36-server.txt)

1. Start an ATM6 dedicated server, default configs and random see '...'
2. Attempt to put an inert crystal into an infuser (following the simple startup guide)
3. Experience sudden sadness and desperation since the server crashed

**ModPack**
ATM6 v.1.3.0

**Comment by Sirttas** [comment] 2020-11-13 19:01
duplicate of https://github.com/Sirttas/ElementalCraft/issues/15

**Closed as completed by Sirttas** 2020-11-13 19:01 UTC
Labels: duplicate
